const p=document.getElementById('player'),marker=document.getElementById('marker'),clock=document.getElementById('clock'),list=document.getElementById('taskList'),count=document.getElementById('taskCount'),msg=document.getElementById('message'),layer=document.getElementById('customerLayer'),custCount=document.getElementById('customers'),prompt=document.getElementById('prompt');
const player={x:610,y:610,r:15,speed:190},keys=new Set();let last=performance.now(),minutes=1320,msgT=0,served=0,inventory=0,scanned=[],checkoutOpen=false,currentCustomer=null,coffeeStep=0,trashOut=false;
const prices={chips:2.49,soda:1.99,candy:1.79,water:1.49};const products={chips:'Potato Chips',soda:'Cola',candy:'Candy',water:'Water'};
const obstacles=[{x:105,y:86,w:270,h:95},{x:105,y:238,w:270,h:95},{x:430,y:86,w:270,h:95},{x:430,y:238,w:270,h:95},{x:780,y:82,w:330,h:105},{x:785,y:345,w:310,h:135},{x:855,y:500,w:110,h:125},{x:80,y:565,w:68,h:82},{x:1020,y:575,w:100,h:143},{x:530,y:645,w:140,h:73}];
const tasks=[{id:'stock',label:'Restock 6 shelf items',x:365,y:205,r:75,msg:'Six shelf items restocked.',done:false},{id:'boxes',label:'Move 3 delivery boxes',x:270,y:440,r:78,msg:'Delivery boxes moved to the stock area.',done:false},{id:'coffee',label:'Clean and reset coffee station',x:910,y:560,r:78,msg:'Coffee station cleaned and reset.',done:false},{id:'trash',label:'Take out the trash',x:115,y:610,r:72,msg:'Trash taken outside.',done:false},{id:'register',label:'Count the register',x:940,y:470,r:82,msg:'Register counted. Everything balances.',done:false},{id:'fridge',label:'Face the drink cooler',x:900,y:205,r:82,msg:'Cooler faced and doors checked.',done:false}];
const customerData=[['CUSTOMER 01',['chips','soda','candy']],['CUSTOMER 02',['water','chips']],['CUSTOMER 03',['soda','water','candy']],['CUSTOMER 04',['candy','water','chips','soda']],['CUSTOMER 05',['chips','water']]];
const customers=customerData.map((d,i)=>({x:610+i*45,y:395+i*30,tx:940,ty:325,state:i===0?'walking':'queued',served:false,name:d[0],items:d[1]}));const els=[];
function money(n){return '$'+n.toFixed(2)}function total(items){return items.reduce((a,k)=>a+prices[k],0)}
function renderTasks(){list.innerHTML=tasks.map(t=>`<div class="task ${t.done?'done':''}"><i class="dot"></i><span>${t.label}</span></div>`).join('');count.textContent=tasks.filter(t=>t.done).length+' / '+tasks.length;document.getElementById('inventory').textContent=inventory;document.getElementById('scanCount').textContent=scanned.length;document.getElementById('total').textContent=money(total(scanned));document.getElementById('coffeeStatus').textContent=coffeeStep===0?'READY':coffeeStep===1?'WIPE':'RESET';document.getElementById('registerPanel').classList.toggle('open',checkoutOpen)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function hit(x,y,r,o){let qx=clamp(x,o.x,o.x+o.w),qy=clamp(y,o.y,o.y+o.h);return(x-qx)**2+(y-qy)**2<r*r}function collide(x,y){return obstacles.some(o=>hit(x,y,player.r,o))||x<60||x>1140||y<60||y>700}function move(dx,dy){if(!collide(player.x+dx,player.y))player.x+=dx;if(!collide(player.x,player.y+dy))player.y+=dy}
function nearestTask(){let b=null,d=1e9;for(const t of tasks)if(!t.done){let n=Math.hypot(player.x-t.x,player.y-t.y);if(n<t.r&&n<d){b=t;d=n}}return b}function nearestCustomer(){return customers.find(c=>!c.served&&c.state==='ready'&&Math.hypot(player.x-c.tx,player.y-c.ty)<105)}function show(s){msg.textContent=s;msg.style.opacity=1;msgT=2.5}
function doTask(t){if(t.id==='boxes'){inventory=6;t.done=true;show(t.msg);renderTasks();return}if(t.id==='stock'){if(inventory<6){show('Pick up the delivery boxes first.');return}inventory-=6;t.done=true;show(t.msg);renderTasks();return}if(t.id==='coffee'){if(coffeeStep===0){coffeeStep=1;show('Wipe the coffee station. Press E again.')}else if(coffeeStep===1){coffeeStep=2;show('Refill the cups and reset the brewer. Press E again.')}else{coffeeStep=0;t.done=true;show(t.msg)}renderTasks();return}if(t.id==='trash'){if(!trashOut){trashOut=true;show('Carry the trash through the front door.');return}else{t.done=true;show(t.msg);renderTasks();return}}t.done=true;show(t.msg);renderTasks()}
function interact(){if(checkoutOpen){show('Finish the checkout panel first.');return}const t=nearestTask();if(t){doTask(t);return}if(trashOut&&Math.hypot(player.x-600,player.y-690)<95){const tt=tasks.find(x=>x.id==='trash');tt.done=true;trashOut=false;show(tt.msg);renderTasks();return}const boxDist=Math.min(Math.hypot(player.x-239,player.y-439),Math.hypot(player.x-324,player.y-439));if(boxDist<80&&inventory<6){inventory=6;show('You picked up 6 mixed shelf items.');renderTasks();return}const c=nearestCustomer();if(c){openCheckout(c);return}show('Nothing needs your attention here.')}
function openCheckout(c){currentCustomer=c;checkoutOpen=true;scanned=[];document.getElementById('customerName').textContent=c.name;document.getElementById('customerItems').innerHTML=c.items.map(k=>`<button data-product="${k}">${products[k]} <b>${money(prices[k])}</b></button>`).join('');renderTasks();show('Scan each item, then choose payment.')}
function finishCheckout(method){if(!currentCustomer||scanned.length!==currentCustomer.items.length){show('Scan every item before taking payment.');return}currentCustomer.served=true;currentCustomer.state='served';served++;custCount.textContent=served;checkoutOpen=false;show(`${method} accepted — ${money(total(scanned))}.`);currentCustomer=null;scanned=[];activateNext();renderTasks()}
function activateNext(){const n=customers.find(c=>!c.served&&c.state==='queued');if(n){n.state='walking';n.x=590;n.y=680}}
document.getElementById('customerItems').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!currentCustomer)return;const k=b.dataset.product;if(scanned.length<currentCustomer.items.length){scanned.push(k);b.disabled=true;b.classList.add('scanned');renderTasks();show(`${products[k]} scanned — ${money(prices[k])}`)}});document.getElementById('cashBtn').onclick=()=>finishCheckout('Cash');document.getElementById('cardBtn').onclick=()=>finishCheckout('Card');document.getElementById('cancelBtn').onclick=()=>{checkoutOpen=false;currentCustomer=null;scanned=[];renderTasks();show('Checkout cancelled.')};
function customerGraphic(c,i){let g=document.createElementNS('http://www.w3.org/2000/svg','g');g.innerHTML=`<ellipse cx="0" cy="16" rx="14" ry="5" fill="#171717" opacity=".42"/><circle cy="-5" r="7" fill="${i%2?'#a98e7e':'#8d7769'}"/><path d="M-7-5q1-11 7-11t7 11q-4-4-7-3t-7 3" fill="${i%2?'#292929':'#151515'}"/><path d="M-10 7q10-7 20 0v13h-20z" fill="${['#4a4a4a','#5b554d','#383838','#68615a'][i%4]}"/>`;layer.appendChild(g);els.push(g)}customers.forEach(customerGraphic);
function updateCustomers(dt){customers.forEach((c,i)=>{if(c.served||c.state==='queued')return;let dx=c.tx-c.x,dy=c.ty-c.y,d=Math.hypot(dx,dy);if(d>10){c.x+=dx/d*42*dt;c.y+=dy/d*42*dt}else c.state='ready';els[i].setAttribute('transform',`translate(${c.x},${c.y})`);els[i].setAttribute('opacity',c.served?'0':1)})}
function updateClock(dt){minutes+=dt*.8;if(minutes>=1800){minutes=1800;clock.textContent='6:00 AM';return}let h=Math.floor((minutes%1440)/60),m=Math.floor(minutes%60),ap=h>=12?'PM':'AM';h=h%12||12;clock.textContent=`${h}:${String(m).padStart(2,'0')} ${ap}`}
function loop(now){let dt=Math.min((now-last)/1000,.05);last=now;let dx=0,dy=0;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;if(dx||dy){let l=Math.hypot(dx,dy);move(dx/l*player.speed*dt,dy/l*player.speed*dt)}updateCustomers(dt);updateClock(dt);let t=nearestTask(),c=nearestCustomer(),trash=trashOut&&Math.hypot(player.x-600,player.y-690)<95;marker.setAttribute('opacity',(t||c||trash)?'1':'0');if(c){marker.setAttribute('transform',`translate(${c.tx},${c.ty-35})`);prompt.textContent='E  CHECK OUT CUSTOMER'}else if(trash){marker.setAttribute('transform','translate(600,655)');prompt.textContent='E  TAKE TRASH OUTSIDE'}else if(t){marker.setAttribute('transform',`translate(${t.x},${t.y-35})`);prompt.textContent=t.id==='coffee'&&coffeeStep>0?'E  CONTINUE CLEANING':'E  INTERACT'}else prompt.textContent='WASD  MOVE   E  INTERACT';p.setAttribute('transform',`translate(${player.x},${player.y})`);if(msgT>0){msgT-=dt;if(msgT<=0)msg.style.opacity=0}requestAnimationFrame(loop)}
addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e'].includes(k))e.preventDefault();keys.add(k);if(k==='e'&&!e.repeat)interact()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));renderTasks();requestAnimationFrame(loop);
